networks:
  app:
    driver: bridge
services:
  redis:
    image: redis:7.2-alpine
    restart: always
    ports:
      - "6100:6379"
    command: redis-server --loglevel warning --requirepass password
    volumes:
      - redis-data:/data
    networks:
      - app

  sator-backend-api:
    build:
      context: .
      dockerfile: deployment/Dockerfile${CUSTOM}
    environment:
      NODE_ENV: ${NODE_ENV}
      PASSWORD_SALT: ${PASSWORD_SALT}
      DEFAULT_PASSWORD: ${DEFAULT_PASSWORD}
      REDIS_URL: ${REDIS_URL}
      PORT: ${PORT}
      SOCKET_PORT: ${SOCKET_PORT}
      LOG_LEVEL: ${LOG_LEVEL}
      ENCRYPTION_KEY: ${ENCRYPTION_KEY}
      DEFAULT_OTP_CODE: ${DEFAULT_OTP_CODE}
      AWS_S3_BUCKET_NAME: ${AWS_S3_BUCKET_NAME}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_ACCESS_KEY: ${AWS_ACCESS_KEY}
      AWS_REGION: ${AWS_REGION}
      AWS_BUCKET_NAME: ${AWS_BUCKET_NAME}
      AWS_PUBLIC_BUCKET_URL: ${AWS_PUBLIC_BUCKET_URL}
      API_KEY_SECRET: ${API_KEY_SECRET}
      API_KEY_ALGO: ${API_KEY_ALGO}
      API_KEY_IV: ${API_KEY_IV}
      DATABASE_URL: ${DATABASE_URL}
    volumes:
      - api-data:/app
    networks:
      - app
    depends_on:
      - redis
    links:
      - redis
    ports:
      - 3100:3000

volumes:
  api-data:
  redis-data: