name: Deploy to Staging with Temporary Database

on:
  workflow_dispatch: # Allows manual triggering
  push:
    branches:
      - main
    paths:
      - "prisma/**"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Apply migrations to staging database
        run: npx prisma migrate deploy
        env:
          DATABASE_URL: ${{ secrets.STAGING_DATABASE_URL }}

      - name: Seed the temporary database
        run: npx prisma db seed
        env:
          DATABASE_URL: ${{ secrets.STAGING_DATABASE_URL }}
