# .github/workflows/deploy.yml
name: Deploy to Staging

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Run Tests"]
    types:
      - completed
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Verify Changed files
        uses: tj-actions/verify-changed-files@v20
        id: verify-changed-files
        with:
          files: |
            prisma/**

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Create .env file for NODE environment
        run: |
          echo "NODE_ENV=staging" > .env

      - name: Apply migrations to staging database
        run: npx prisma migrate deploy
        env:
          DATABASE_URL: ${{ secrets.STAGING_DATABASE_URL }}

      - name: Seed the staging database
        run: npx prisma db seed
        env:
          DATABASE_URL: ${{ secrets.STAGING_DATABASE_URL }}
