name: Run Tests

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "src/**"
      - "tests/**"
      - ".github/workflows/**"

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: testuser
          POSTGRES_PASSWORD: testpassword
          POSTGRES_DB: testdb
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      redis:
        image: redis:latest
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Create .env file for temporary database
        run: |
          echo "DATABASE_URL=postgresql://testuser:testpassword@localhost:5432/testdb" > .env
          echo "REDIS_URL=redis://localhost:6379" >> .env
          echo "PORT=3000" >> .env
          echo "SOCKET_PORT=8080" >> .env
          echo "PASSWORD_SALT=11" >> .env
          echo "DEFAULT_OTP_CODE=666666" >> .env
          echo "API_KEY_SECRET=4b86193e4f4a80f3f34af2f2466fdee00d1bdc7e926e9e0c103b92b82cd2d102" >> .env
          echo "API_KEY_IV=1be6f547fc84c37c30dbf9be193ebccd" >> .env
          echo "API_KEY_ALGO=aes-256-cbc" >> .env

      - name: Run migrations on temporary database
        run: npx prisma migrate deploy

      - name: Seed the temporary database
        run: npx prisma db seed -- --environment test

      - name: Run tests
        run: npm test
